"""Alembic 迁移检查（spec：schema 可从空数据库创建；PG 方言校验为 integration 层）。"""

import os

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect

_ALEMBIC_INI = "apps/api/alembic.ini"


def test_migration_creates_schema_from_empty_database(tmp_path, monkeypatch):
    # 隔离宿主环境：env.py 会用 MEDICALRAG_DATABASE_URL 覆盖 ini，这里显式清除。
    monkeypatch.delenv("MEDICALRAG_DATABASE_URL", raising=False)
    db_file = tmp_path / "migration.db"
    config = Config(_ALEMBIC_INI)
    config.set_main_option("sqlalchemy.url", f"sqlite+aiosqlite:///{db_file}")
    command.upgrade(config, "head")

    inspector = inspect(create_engine(f"sqlite:///{db_file}"))
    tables = set(inspector.get_table_names())
    assert {
        "chat_runs",
        "run_events",
        "messages",
        "users",
        "intent_nodes",
        "ingestion_runs",
        "ingestion_run_stages",
    } <= tables
    # 已删除的无引用遗留表不得回归
    assert "slot_schemas" not in tables


def test_migration_matches_orm_metadata(tmp_path, monkeypatch):
    """迁移结果必须与 ORM 模型一致（挡 schema 漂移：加列/索引漏写迁移，或建表未加模型）。"""
    monkeypatch.delenv("MEDICALRAG_DATABASE_URL", raising=False)
    db_file = tmp_path / "drift.db"
    config = Config(_ALEMBIC_INI)
    config.set_main_option("sqlalchemy.url", f"sqlite+aiosqlite:///{db_file}")
    command.upgrade(config, "head")
    # 有漂移时抛 AutogenerateDiffsDetected（列在异常信息中）
    command.check(config)


def test_migration_downgrades_to_empty_schema(tmp_path, monkeypatch):
    """回滚安全：head → base 后不残留业务表（迁移链必须可往返，否则发布回滚无路可走）。"""
    monkeypatch.delenv("MEDICALRAG_DATABASE_URL", raising=False)
    db_file = tmp_path / "rollback.db"
    config = Config(_ALEMBIC_INI)
    config.set_main_option("sqlalchemy.url", f"sqlite+aiosqlite:///{db_file}")
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    tables = set(inspect(create_engine(f"sqlite:///{db_file}")).get_table_names())
    assert tables <= {"alembic_version"}


@pytest.mark.integration
@pytest.mark.skipif(
    not os.environ.get("MEDICALRAG_TEST_DATABASE_URL"),
    reason="需要 MEDICALRAG_TEST_DATABASE_URL（compose --profile test）",
)
def test_migration_matches_orm_metadata_on_real_postgres(monkeypatch):
    """PG 方言漂移门禁：JSONB/server_default/方言索引等差异在 SQLite 侧不可见，须在真 PG 上校验。"""
    monkeypatch.delenv("MEDICALRAG_DATABASE_URL", raising=False)
    config = Config(_ALEMBIC_INI)
    config.set_main_option("sqlalchemy.url", os.environ["MEDICALRAG_TEST_DATABASE_URL"])
    command.upgrade(config, "head")
    command.check(config)
