/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminIngestionRouteImport } from './routes/admin/ingestion'
import { Route as AdminIntentsRouteImport } from './routes/admin/intents'
import { Route as AdminKnowledgeRouteImport } from './routes/admin/knowledge'
import { Route as AdminMappingsRouteImport } from './routes/admin/mappings'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTracesRouteImport } from './routes/admin/traces'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminKnowledgeIndexRouteImport } from './routes/admin/knowledge.index'
import { Route as AdminKnowledgeKbIdRouteImport } from './routes/admin/knowledge.$kbId'
import { Route as AdminTracesIndexRouteImport } from './routes/admin/traces.index'
import { Route as AdminTracesRunIdRouteImport } from './routes/admin/traces.$runId'
import { Route as AdminKnowledgeKbIdIndexRouteImport } from './routes/admin/knowledge.$kbId.index'
import { Route as AdminKnowledgeKbIdDocsDocIdRouteImport } from './routes/admin/knowledge.$kbId.docs.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIngestionRoute = AdminIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntentsRoute = AdminIntentsRouteImport.update({
  id: '/intents',
  path: '/intents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMappingsRoute = AdminMappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTracesRoute = AdminTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeIndexRoute = AdminKnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminKnowledgeRoute,
} as any)
const AdminKnowledgeKbIdRoute = AdminKnowledgeKbIdRouteImport.update({
  id: '/$kbId',
  path: '/$kbId',
  getParentRoute: () => AdminKnowledgeRoute,
} as any)
const AdminTracesIndexRoute = AdminTracesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTracesRoute,
} as any)
const AdminTracesRunIdRoute = AdminTracesRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AdminTracesRoute,
} as any)
const AdminKnowledgeKbIdIndexRoute = AdminKnowledgeKbIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminKnowledgeKbIdRoute,
} as any)
const AdminKnowledgeKbIdDocsDocIdRoute =
  AdminKnowledgeKbIdDocsDocIdRouteImport.update({
    id: '/docs/$docId',
    path: '/docs/$docId',
    getParentRoute: () => AdminKnowledgeKbIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/intents': typeof AdminIntentsRoute
  '/admin/knowledge': typeof AdminKnowledgeRouteWithChildren
  '/admin/mappings': typeof AdminMappingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/traces': typeof AdminTracesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/knowledge/$kbId': typeof AdminKnowledgeKbIdRouteWithChildren
  '/admin/traces/$runId': typeof AdminTracesRunIdRoute
  '/admin/knowledge/': typeof AdminKnowledgeIndexRoute
  '/admin/traces/': typeof AdminTracesIndexRoute
  '/admin/knowledge/$kbId/': typeof AdminKnowledgeKbIdIndexRoute
  '/admin/knowledge/$kbId/docs/$docId': typeof AdminKnowledgeKbIdDocsDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/intents': typeof AdminIntentsRoute
  '/admin/mappings': typeof AdminMappingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/traces/$runId': typeof AdminTracesRunIdRoute
  '/admin/knowledge': typeof AdminKnowledgeIndexRoute
  '/admin/traces': typeof AdminTracesIndexRoute
  '/admin/knowledge/$kbId': typeof AdminKnowledgeKbIdIndexRoute
  '/admin/knowledge/$kbId/docs/$docId': typeof AdminKnowledgeKbIdDocsDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/status': typeof StatusRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/intents': typeof AdminIntentsRoute
  '/admin/knowledge': typeof AdminKnowledgeRouteWithChildren
  '/admin/mappings': typeof AdminMappingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/traces': typeof AdminTracesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/knowledge/$kbId': typeof AdminKnowledgeKbIdRouteWithChildren
  '/admin/traces/$runId': typeof AdminTracesRunIdRoute
  '/admin/knowledge/': typeof AdminKnowledgeIndexRoute
  '/admin/traces/': typeof AdminTracesIndexRoute
  '/admin/knowledge/$kbId/': typeof AdminKnowledgeKbIdIndexRoute
  '/admin/knowledge/$kbId/docs/$docId': typeof AdminKnowledgeKbIdDocsDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/status'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/ingestion'
    | '/admin/intents'
    | '/admin/knowledge'
    | '/admin/mappings'
    | '/admin/settings'
    | '/admin/traces'
    | '/admin/users'
    | '/admin/'
    | '/admin/knowledge/$kbId'
    | '/admin/traces/$runId'
    | '/admin/knowledge/'
    | '/admin/traces/'
    | '/admin/knowledge/$kbId/'
    | '/admin/knowledge/$kbId/docs/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/status'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/ingestion'
    | '/admin/intents'
    | '/admin/mappings'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/admin/traces/$runId'
    | '/admin/knowledge'
    | '/admin/traces'
    | '/admin/knowledge/$kbId'
    | '/admin/knowledge/$kbId/docs/$docId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/status'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/ingestion'
    | '/admin/intents'
    | '/admin/knowledge'
    | '/admin/mappings'
    | '/admin/settings'
    | '/admin/traces'
    | '/admin/users'
    | '/admin/'
    | '/admin/knowledge/$kbId'
    | '/admin/traces/$runId'
    | '/admin/knowledge/'
    | '/admin/traces/'
    | '/admin/knowledge/$kbId/'
    | '/admin/knowledge/$kbId/docs/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ingestion': {
      id: '/admin/ingestion'
      path: '/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AdminIngestionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/intents': {
      id: '/admin/intents'
      path: '/intents'
      fullPath: '/admin/intents'
      preLoaderRoute: typeof AdminIntentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mappings': {
      id: '/admin/mappings'
      path: '/mappings'
      fullPath: '/admin/mappings'
      preLoaderRoute: typeof AdminMappingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/traces': {
      id: '/admin/traces'
      path: '/traces'
      fullPath: '/admin/traces'
      preLoaderRoute: typeof AdminTracesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge/': {
      id: '/admin/knowledge/'
      path: '/'
      fullPath: '/admin/knowledge/'
      preLoaderRoute: typeof AdminKnowledgeIndexRouteImport
      parentRoute: typeof AdminKnowledgeRoute
    }
    '/admin/knowledge/$kbId': {
      id: '/admin/knowledge/$kbId'
      path: '/$kbId'
      fullPath: '/admin/knowledge/$kbId'
      preLoaderRoute: typeof AdminKnowledgeKbIdRouteImport
      parentRoute: typeof AdminKnowledgeRoute
    }
    '/admin/traces/': {
      id: '/admin/traces/'
      path: '/'
      fullPath: '/admin/traces/'
      preLoaderRoute: typeof AdminTracesIndexRouteImport
      parentRoute: typeof AdminTracesRoute
    }
    '/admin/traces/$runId': {
      id: '/admin/traces/$runId'
      path: '/$runId'
      fullPath: '/admin/traces/$runId'
      preLoaderRoute: typeof AdminTracesRunIdRouteImport
      parentRoute: typeof AdminTracesRoute
    }
    '/admin/knowledge/$kbId/': {
      id: '/admin/knowledge/$kbId/'
      path: '/'
      fullPath: '/admin/knowledge/$kbId/'
      preLoaderRoute: typeof AdminKnowledgeKbIdIndexRouteImport
      parentRoute: typeof AdminKnowledgeKbIdRoute
    }
    '/admin/knowledge/$kbId/docs/$docId': {
      id: '/admin/knowledge/$kbId/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/admin/knowledge/$kbId/docs/$docId'
      preLoaderRoute: typeof AdminKnowledgeKbIdDocsDocIdRouteImport
      parentRoute: typeof AdminKnowledgeKbIdRoute
    }
  }
}

interface AdminKnowledgeKbIdRouteChildren {
  AdminKnowledgeKbIdIndexRoute: typeof AdminKnowledgeKbIdIndexRoute
  AdminKnowledgeKbIdDocsDocIdRoute: typeof AdminKnowledgeKbIdDocsDocIdRoute
}

const AdminKnowledgeKbIdRouteChildren: AdminKnowledgeKbIdRouteChildren = {
  AdminKnowledgeKbIdIndexRoute: AdminKnowledgeKbIdIndexRoute,
  AdminKnowledgeKbIdDocsDocIdRoute: AdminKnowledgeKbIdDocsDocIdRoute,
}

const AdminKnowledgeKbIdRouteWithChildren =
  AdminKnowledgeKbIdRoute._addFileChildren(AdminKnowledgeKbIdRouteChildren)

interface AdminKnowledgeRouteChildren {
  AdminKnowledgeKbIdRoute: typeof AdminKnowledgeKbIdRouteWithChildren
  AdminKnowledgeIndexRoute: typeof AdminKnowledgeIndexRoute
}

const AdminKnowledgeRouteChildren: AdminKnowledgeRouteChildren = {
  AdminKnowledgeKbIdRoute: AdminKnowledgeKbIdRouteWithChildren,
  AdminKnowledgeIndexRoute: AdminKnowledgeIndexRoute,
}

const AdminKnowledgeRouteWithChildren = AdminKnowledgeRoute._addFileChildren(
  AdminKnowledgeRouteChildren,
)

interface AdminTracesRouteChildren {
  AdminTracesRunIdRoute: typeof AdminTracesRunIdRoute
  AdminTracesIndexRoute: typeof AdminTracesIndexRoute
}

const AdminTracesRouteChildren: AdminTracesRouteChildren = {
  AdminTracesRunIdRoute: AdminTracesRunIdRoute,
  AdminTracesIndexRoute: AdminTracesIndexRoute,
}

const AdminTracesRouteWithChildren = AdminTracesRoute._addFileChildren(
  AdminTracesRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminIngestionRoute: typeof AdminIngestionRoute
  AdminIntentsRoute: typeof AdminIntentsRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRouteWithChildren
  AdminMappingsRoute: typeof AdminMappingsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTracesRoute: typeof AdminTracesRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminIngestionRoute: AdminIngestionRoute,
  AdminIntentsRoute: AdminIntentsRoute,
  AdminKnowledgeRoute: AdminKnowledgeRouteWithChildren,
  AdminMappingsRoute: AdminMappingsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTracesRoute: AdminTracesRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
