"""创建文档摄取运行记录表 ingestion_runs 与各阶段追踪表 ingestion_run_stages。

Revision ID: 06777a5c1234
Revises: cb4e3910cf17
Create Date: 2026-08-01 22:00:18.003579

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06777a5c1234"
down_revision: str | Sequence[str] | None = "cb4e3910cf17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """应用数据库升级迁移：创建 ingestion_runs 与 ingestion_run_stages 表。"""
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_runs_document_id"), "ingestion_runs", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_runs_workspace_id"), "ingestion_runs", ["workspace_id"], unique=False
    )
    op.create_table(
        "ingestion_run_stages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "stage", name="uq_ingestion_run_stage"),
    )
    op.create_index(
        op.f("ix_ingestion_run_stages_run_id"), "ingestion_run_stages", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_run_stages_run_id"), table_name="ingestion_run_stages")
    op.drop_table("ingestion_run_stages")
    op.drop_index(op.f("ix_ingestion_runs_workspace_id"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_document_id"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    # ### end Alembic commands ###
