"""创建医学意图节点表 intent_nodes（支持层级树结构、少样本示例、Prompt 片段与安全等级分类）。

Revision ID: cb4e3910cf17
Revises: 3c09284d86b7
Create Date: 2026-08-01 21:42:31.163452

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb4e3910cf17"
down_revision: str | Sequence[str] | None = "3c09284d86b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """应用数据库升级迁移：创建 intent_nodes 表。"""
    op.create_table(
        "intent_nodes",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.String(length=128), nullable=True),
        sa.Column("examples", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("prompt_snippet", sa.Text(), nullable=True),
        sa.Column("prompt_template", sa.Text(), nullable=True),
        sa.Column("safety_class", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("intent_nodes")
    # ### end Alembic commands ###
